### ISSUE TITLE
Directory restructuring to decouple library and ROS layer

### ISSUE THREAD

**Issue by mlsdpk** [mlsdpk/slam_vdb#1]
# Description
The existing directory structure is designed to be built as a single ROS package, including library implementations inside. This approach couples the implementation and ROS layer, relying on ROS and making it difficult to maintain and release for different ROS distributions.

# Purpose
The task is to decouple these two and separate them into different directory structures while maintaining the building of the modules inside the same workspace.

# Possible approaches
N/A

# Definition of done
- [x] Two directories responsible for the library implementation and ROS2 layer
- [ ] Able to build both inside the workspace using colcon
- [x] Able to build the library implementation using make
- [ ] Proper build files to handle dependencies correctly

**Comment by ghanta1996** [comment]
#6  addresses this issue
